name: Full Project Setup

on:
  workflow_dispatch:  # Allows manual run
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Create directory structure
      run: |
        mkdir -p session-transfer
        mkdir -p session-transfer/sessions
        chmod 700 session-transfer/sessions

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install dependencies (keeping all files)
      working-directory: ./session-transfer
      run: |
        composer require guzzlehttp/guzzle --no-interaction --no-progress --no-ignore-platform-reqs
        composer dump-autoload

    - name: Commit EVERYTHING (including vendor)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Add complete project with all files"
        git push
