name: Project Setup

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create directory structure
      run: |
        mkdir -p session-transfer
        chmod 755 session-transfer
        
    - name: Install dependencies
      working-directory: ./session-transfer
      run: |
        composer require guzzlehttp/guzzle --no-interaction --no-progress
        
    - name: Create sessions directory
      run: |
        mkdir -p session-transfer/sessions
        chmod 700 session-transfer/sessions
        
    - name: Add .gitignore
      run: |
        echo "vendor/" >> session-transfer/.gitignore
        echo ".env" >> session-transfer/.gitignore
        echo "sessions/*" >> session-transfer/.gitignore
