name: Full Project Setup

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full git history

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Create project structure
      run: |
        # Force create all directories
        mkdir -p session-transfer/sessions
        chmod 700 session-transfer/sessions
        
        # Create minimal composer.json if not exists
        if [ ! -f "session-transfer/composer.json" ]; then
          echo '{"require":{}}' > session-transfer/composer.json
        fi

    - name: Install dependencies
      working-directory: ./session-transfer
      run: |
        # Force install dependencies
        composer require guzzlehttp/guzzle --no-interaction --no-progress --ignore-platform-reqs
        composer dump-autoload -o
        
        # Create test file to ensure sessions directory is tracked
        touch sessions/.keep

    - name: Force add all files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -f .
        git status
        git commit -m "Add complete project structure with vendor" || exit 0
        git push
